Etv\TestBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Etv\TestBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        firtname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        roles:
            type: string
            length: 255
    lifecycleCallbacks: {  }
