Etv\TestBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Etv\TestBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        roles:
            type: string
            length: 255
            nullable: no
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        modifiedAt:
            type: datetime
            column: modify_at
            gedmo:
                timestampable:
                    on: update
        dateOfBirth:
            type: date
            column: date_of_birth
        type:
            type: smallint
            nullable: false
    lifecycleCallbacks: {  }
