parameters:
#    etv_test.example.class: Etv\TestBundle\Example

services:
#    etv_test.example:
#        class: %etv_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
